language: python
python:
  - "3.6"
# command to install dependencies
install: 
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install codecov
# command to run tests
script:
  - pytest --cov=./
#  - coverage run --source=project test_Services.py
  
#  coverage run --source=Guests test.py
after_success:
  - coveralls
  - codecov
